version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cognitoDependanciesLibraryApp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-rf2vqva48wgd"
s3_prefix = "cognitoDependanciesLibraryApp"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
