/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_9iKtaxPc8",
    "aws_user_pools_web_client_id": "5icvm7oeh07beqiopgkedntnss",
    "oauth": {}
};


export default awsmobile;
